import tkinter
win=tkinter.Tk()
win.title('Synnefo')
win.geometry('400x400')
win.minsize(100,100)
win.maxsize(600,600)
win.config(background='red')
def data():
    12=tkinter.Label(win)
    l2.pack()
    

l1=tkinter.Label(win,text='welcome')
l2=tkinter.Label(win,text='you choose python')
l3=tkinter.Label(win,text='Python is highlevel language')
# l1.grid(row=0,column=0)
# l2.grid(row=0,column=0)
# l3.grid(row=0,column=0)
l1.pack()
el=tkinter.Entry(win)
el.pack()
b1=tkinter.Button(win,text='submit')
b1.pack()
v1=tkinter.IntVar()
c1=tkinter.Checkbutton(win,text='sslc')
c1.pack()
v2=tkinter.IntVar()
c2=tkinter.Checkbutton(win,text='plus two')
c2.pack()
v3=tkinter.IntVar()
c3=tkinter.Checkbutton(win,text='degree')
c3.pack()
win.mainloop()